name: CI/CD for Azure Function App

on:
  push:
    branches: [ master ]
    paths:
    - 'backend/**'

env:
  AZURE_FUNCTIONAPP_NAME: 'ShipShapeFA'           # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'       # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.11'                          # set this to the python version to use (e.g. '3.6', '3.7', '3.8')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Install Dependencies'
      run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/api/requirements.txt

    - name: 'Set PYTHONPATH'
      run: echo "PYTHONPATH=${{ github.workspace }}/${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}" >> $GITHUB_ENV
  
    - name: 'Run Unit Tests'
      run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/tests
          python -m unittest discover -s . -p '*_test.py'

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/api
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true